woowacourse-teams/2021-gpu-is-mine

.gitignore, back-end/.gitignore, back-end/build.gradle, back-end/src/main/resources/application-dev.properties, back-end/src/main/resources/application-local.properties, back-end/src/main/resources/application-prod.properties, back-end/src/main/resources/application.properties, back-end/src/main/resources/logback-access.xml, back-end/src/main/resources/logback-spring.xml
close #38 
[wiki : 우리팀 로깅 설정](https://github.com/woowacourse-teams/2021-gpu-is-mine/wiki/우리-팀의-로깅-전략)
=> feat: 로깅 설정

back-end/auto-script-dev.sh, back-end/auto-script-prod.sh, back-end/auto-script.sh
=> chore: 젠킨스 빌드 자동화를 위한 실행 스크립트 작성

front-end/.storybook/preview.js, front-end/src/components/Flicker/Flicker.tsx, front-end/src/components/ServerIcon/ServerIcon.styled.ts, front-end/src/components/ServerIcon/ServerIcon.tsx, front-end/src/components/index.ts, front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.stories.tsx, front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.styled.ts, front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.tsx, front-end/src/fixtures/gpuServersResponse.ts
=> feat: GPU 서버 전체 조회 관련 컴포넌트 구현

.github/workflows/gradle.yml
jenkins로 진행하려고 했으나,
전달해서  build 하는 부분까진 성공했으나, build 된 정보를 PR 정보에 쓰기 부분에서 권한 issue 발생. 추후에 jenkins로 했으면 좋겠음..
- github action으로 PR 요청시 build test 진행
- jenkins를 활용하여 PR 머지 후 배포 진행
요정도 flow 로 생각하면 될것 같아요.
=> chore: PR시 github action으로 build 테스트 진행

front-end/.eslintrc.js, front-end/package.json, front-end/src/components/Button/Button.styled.ts, front-end/src/components/Input/Input.stories.tsx, front-end/src/components/Input/Input.styled.ts, front-end/src/components/Input/Input.tsx, front-end/src/domains/GpuServerAddForm/GpuServerAddForm.stories.tsx, front-end/src/domains/GpuServerAddForm/GpuServerAddForm.styled.ts, front-end/src/domains/GpuServerAddForm/GpuServerAddForm.tsx, front-end/src/hooks/useForm/useForm.ts, front-end/src/styles/GlobalStyle.tsx, front-end/src/styles/colors.ts, front-end/src/types/util.ts, front-end/yarn.lock
=> feat: GpuServer 등록폼 컴포넌트 구현

front-end/src/domains/ManagerHeader/ManagerHeader.styled.ts, front-end/src/domains/ManagerSubHeader/ManagerSubHeader.styled.ts, front-end/src/pages/manager/GpuServerView/GpuServerView.styled.ts
=> fix: styled-breakpoints 마이그레이션으로 인한 에러 수정(fix #88)

back-end/src/main/java/admin/WebConfig.java
=> feat: cors 모든 경우 허용

back-end/src/main/java/admin/gpuserver/application/GpuServerService.java, back-end/src/main/java/admin/gpuserver/exception/GpuServerServiceException.java, back-end/src/main/java/admin/gpuserver/ui/GpuServerController.java, back-end/src/test/java/admin/gpuserver/application/GpuServerServiceTest.java
closes #114 
GpuServer Exception이 두 개가 있어 핸들링이 안되고 있었음을 확인했습니다.
Exception 명을 바꾸고 merge 과정에서 파일이 두 개가 생긴 것 같습니다.
=> fix: GpuServerException Handler 오류 해결

.gitignore, front-end/netlify.toml
FE 배포서버인 netlify 에서 SPA를 지원하기 위한 Redirect 설정입니다.
=> chore: netlify redirect 설정

front-end/src/constants/api.ts
- ERR_CERT_COMMON_NAME_INVALID
close #122
=> fix: api url 변경

back-end/src/main/java/admin/config/SwaggerConfig.java, back-end/src/main/java/admin/config/WebConfig.java, back-end/src/main/resources/application-dev.properties, back-end/src/main/resources/application-local.properties, back-end/src/main/resources/application-prod.properties, back-end/src/main/resources/application.properties, back-end/src/main/resources/logback-access.xml, back-end/src/main/resources/logback-spring.xml
1. log.log 파일의 sql query param 부분 제거했습니다.
2. local에서 show.sql의 기본 값을 false로 수정했습니다.
3. http 요청, 응답 시 body가 안 나오던 문제를 수정했습니다.
4. 기존 log.log 파일이 사실 http 요청, 응답 로그를 더하였습니다. 
확인 필요.
- Unhandled Exception의 Http response로 에러 자체를 반환하고 있습니다.
- 개인적으로는 처리하지 않은 에러를 직접 던지는 것은 매우 위험하다고 생각하는데(ex, sql error), 이 부분 의도하신건지 궁금합니다.
=> Chore: 로깅 설정을 수정한다.

back-end/auto-script-dev.sh, back-end/auto-script-prod.sh
Close #135 
추가로 prod 환경에도 openJdk를 설치하고 스크립트 변경할까 고민했습니다.
아직 하지 않았는데, 특별히 반대 의견 없으면 이 PR 안에서 처리하고 싶은데 혹시 반대하시는 분 계시나요?
```
#!/bin/bash
echo "> now ing app pid find!"
CURRENT_PID=$(pgrep -f back-end)
echo "$CURRENT_PID"
if [ -z $CURRENT_PID ]; then
echo "> no ing app."
else
echo "> kill -9 $CURRENT_PID"
kill -9 $CURRENT_PID
sleep 3
fi
echo "> new app deploy"
JAR_NAME=$(ls |grep 'back-end' | tail -n 1)
echo "> JAR Name: $JAR_NAME"
#JAVA=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
nohup java -jar -Dspring.profiles.active=dev $JAR_NAME &
sleep 3
```
=> chore: dev 환경의 java 위치 변동에 따른, auto script 수정

back-end/src/main/java/admin/DataLoader.java
데모 데이 시연을 위한 작업이었습니다.
프론트엔드 크루들의 개발 편의를 생각하여 초기 seed 데이터를 추가했습니다. 
dev 환경에서만 적용시켰습니다.
리뷰 부탁드리고, 불필요한 작업이라고 생각되시면 반영 안 해도 되니 편하게 말씀 부탁드립니다.
=> chore: 개발 편의를 위한 초기 seed 데이터 추가

.github/workflows/gpu-is-mine-CI.yml
오타로 인해 build 되지 않는 문제 발생
:`chekstyleTest` -> `checkstyleTest` 오타수정
=> fixed: checkstyleTest 오타 수정

front-end/src/__mocks__/handlers.ts, front-end/src/constants/api.ts, front-end/src/domains/JobRegisterForm/JobRegisterForm.tsx, front-end/src/hooks/useAuth/useAuth.ts
+ 간단하게 job등록 url 주소 변경된 것만 PR 날리겠습니다
=> fix: job 등록 API url 변경

back-end/src/main/java/admin/DataLoader.java
=>  chore: 사용자 비밀번호 암호화에 따른, 시드 데이터 저장 방식 수정

back-end/src/main/java/admin/job/application/JobService.java, back-end/src/main/java/admin/job/ui/JobController.java, back-end/src/main/java/admin/worker/domain/repository/LogRepository.java, back-end/src/main/java/admin/worker/dto/LogsResponse.java, back-end/src/test/java/admin/job/application/JobServiceTest.java
Close #205 
데모데이를 위해 임시로 만들어 놓은 값입니다
확인을 위해서 테스트 코드 자체를 비효율적이게 짯으므로 해당 부분을 제외하고 봐주시면 감사하겠습니다
해당 내용은 ERT와 같은 로그 툴 도입 시 다르게 제작될 예정입니다
=> feat: 하나의 잡에 대한 모든 로그 출력 API 추가

back-end/src/main/java/admin/DataLoader.java, back-end/src/main/java/admin/job/application/JobService.java, back-end/src/main/java/admin/job/domain/Job.java, back-end/src/main/java/admin/job/dto/response/JobResponse.java, back-end/src/main/java/admin/job/exception/JobException.java, back-end/src/test/java/admin/job/application/JobServiceTest.java, back-end/src/test/java/admin/job/domain/JobTest.java, back-end/src/test/java/admin/job/ui/JobAcceptanceTest.java, back-end/src/test/java/admin/lab/application/LabServiceTest.java, back-end/src/test/java/admin/member/domain/MemberTest.java, back-end/src/test/java/admin/worker/JobRepositoryTest.java, back-end/src/test/java/admin/worker/application/WorkerServiceTest.java
=> refactor: Job field 추가

back-end/src/main/java/mine/is/gpu/config/SwaggerConfig.java
패키지 변경에 따라 스웨거 베이스 패키지 수정이 필요했는데, 그 부분에서 오타가 있어 스웨거가 안되는 상황이었습니다.
프론트엔드 작업에 급한 문제니 빠르게 merge 하겠습니다.
=> chore: 패키지 변경에 따른 스웨거 베이스 패키지 수정

.github/workflows/gpu-is-mine-CI.yml, front-end/.gitignore, front-end/netlify.toml
=> chore: github actions 에서 storybook deploy를 제외한다 

front-end/src/__fixtures__/authContext.ts, front-end/src/__fixtures__/index.ts, front-end/src/__fixtures__/memberResponses.ts, front-end/src/__mocks__/handlers.ts, front-end/src/components/PrivateRoute/PrivateRoute.tsx, front-end/src/components/PublicRoute/PublicRoute.tsx, front-end/src/hooks/useAuth/useAuth.test.ts, front-end/src/hooks/useAuth/useAuth.ts
=> feat: 새로고침하여도 기존의 url을 유지한다

back-end/src/main/java/mine/is/gpu/DataLoader.java, back-end/src/main/resources/application-dev.properties, back-end/src/main/resources/application-prod.properties
1. flyway properties 수정
2. dataloader 미적용
=> hotfix : flyway 초기 도입 문제 해결

back-end/src/main/resources/application-dev.properties, back-end/src/main/resources/application-prod.properties
flyway 도입에 따른 application 설정 파일 수정
=> chore : flyway 도입에 따른 application 설정 파일 수정

back-end/auto-script-rolling-deployment.sh, back-end/src/main/resources/db/migration/V1__Initialize_project_tables.sql
udpated_time -> completed_time
=> hotfix : flyway init table 수정

front-end/src/app/App.tsx, front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.styled.ts, front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.tsx
close #307 
- 수정 버튼 제거
- 삭제 버튼 색깔 변경
- 상제 조회를 위한 라우터 추가
=> feat: GPU 상세 조회를 위한 버튼 추가 (연구원 및 관리자)

front-end/src/domains/JobDetailLogContent/JobDetailLogContent.tsx
=> feat: Job 로그를 개행하여 로그 콘솔에 표시한다

back-end/auto-script-prod.sh, back-end/build.gradle
=> chore: production script 수정

back-end/src/main/resources/application.properties
=> feat: JSON 응답 gzip 압축 적용

README.md
=> docs: README.md 의 테크로그에 FE 성능 최적화 링크를 추가한다

.github/workflows/gpu-is-mine-CI.yml
=> chore: github action의 각 job을 병렬로 실행시킨다

back-end/build.gradle
- log4j 대응: 내부 의존성 있어 버전 2.15 변경
=> hotfix: log4j 대응
